{
 "title": "制品库运行监控大盘",
 "tags": [ "bkrepo" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "服务",
    "query": "show tag values from jvm_memory_used with key = \"service\""
   },
   {
    "name": "instance",
    "label": "实例",
    "query": "show tag values from jvm_memory_used with key = \"instance\" where service = '$service'"
   }
  ]
 },
 "panels": [
  { "title": "制品库传输状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IO传输平均吞吐",
   "type": "graph",
   "description": "IO传输平均吞吐",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "下载",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "artifact_downloaded_consume",
     "query": "SELECT mean(\"value\")/60 FROM \"artifact_downloaded_consume\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'size') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "size" }
     ]
    },
    {
     "alias": "上传",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "artifact_uploaded_consume",
     "query": "SELECT mean(\"value\") FROM \"artifact_downloaded_consume\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "size" }
     ]
    }
   ]
  },
  {
   "title": "IO传输瞬时吞吐",
   "type": "graph",
   "description": "IO传输瞬时吞吐",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "下载",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "artifact_downloaded_consume",
     "query": "SELECT mean(\"value\")/mean(\"sum\")*1000 FROM \"artifact_downloaded_consume\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "上传",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "artifact_downloaded_consume",
     "query": "SELECT mean(\"value\")/mean(\"sum\")*1000 FROM \"artifact_uploaded_consume\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "构件传输(平均1分钟)",
   "type": "graph",
   "description": "平均每秒传输数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "下载",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "artifact_downloaded_consume",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "上传",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "artifact_uploaded_consume",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "构件传输瞬时数量",
   "type": "graph",
   "description": "记录某个时间点的瞬时传输数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "下载",
     "measurement": "artifact_downloading_count",
     "query": "SELECT \"value\" FROM \"autogen\".\"artifact_downloading_count\" WHERE (\"service\" =~ /^$service$/ AND \"instance\" =~ /^$instance$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "上传",
     "measurement": "artifact_uploading_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "异步任务状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "异步任务实时数量",
   "type": "graph",
   "description": "异步任务实时数量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "measurement": "async_task_active_count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "异步任务队列大小",
   "type": "graph",
   "description": "异步任务队列大小",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "大小",
     "measurement": "async_task_queue_size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}