{{- if .Values.job.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-job
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: job
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    job.repoRefreshJobProperties.concurrentLevel: COLLECTION
    job.repoRefreshJobProperties.permitsPerSecond: 512
    job.repoRefreshJobProperties.types: HELM,OCI
    job.deleted-node-cleanup.deletedNodeReserveDays: {{ .Values.repository.config.deletedNodeReserveDays }}
    job.artifact-cleanup.enabled: true
{{- end }}