package com.tencent.bkrepo.npm.constants

// package.json
const val ID = "_id"
const val REV = "_rev"
const val REV_VALUE = "1-0"
const val NAME = "name"
const val DESCRIPTION = "description"
const val DISTTAGS = "dist-tags"
const val LATEST = "latest"
const val VERSIONS = "versions"
const val VERSION = "version"
const val KEYWORDS = "keywords"
const val DEPENDENCIES = "dependencies"
const val DEV_DEPENDENCIES = "devDependencies"
const val DIST = "dist"
const val TARBALL = "tarball"
const val SHASUM = "shasum"
const val README = "readme"
const val ATTACHMENTS = "_attachments"
const val CONTENT_TYPE = "content_type"
const val DATA = "data"
const val LENGTH = "length"

const val METADATA = "metadata"
const val MAINTAINERS = "maintainers"
const val AUTHOR = "author"
const val PACKAGE = "package"
const val OBJECTS = "objects"

const val TIME = "time"
const val CREATED = "created"
const val MODIFIED = "modified"
const val LAST_MODIFIED_DATE = "lastModifiedDate"

// auth
const val PASSWORD = "password"
const val TYPE = "type"
const val ROLES = "roles"
const val DATE = "data"
const val USERNAME = "username"
