package com.tencent.bkrepo.repository.event

enum class EventType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,

    REPO_CREATED,
    REPO_UPDATED,
    REPO_DELETED,

    NODE_CREATED,
    NODE_UPDATED,
    NODE_DELETED,
    NODE_RENAMED,
    NODE_COPIED,
    NODE_MOVED,

    METADATA_CREATED,
    METADATA_UPDATED,
    METADATA_DELETED
}