version: "v2.0"
name: "PR CHECK"

on:
  mr:
    target-branches:  [ "master" ]

stages:
- name: "PR检查"
  label:
    - "Build"
  check-out:
    gates:
      - template: codecc_pr_check.yml
      
  jobs:
    job_1:
      name: "源代码规范性检查"
      runs-on:
        needs:
          jdk: "1.8.0_161"
      steps:
        - checkout: self
        - name: "kotlin代码规范检查"
          run: |
            cd src/backend/
            wget https://github.com/pinterest/ktlint/releases/download/0.29.0/ktlint -O ktlint
            java -jar ktlint "**/src/**/*.kt" --reporter=plain,output=report/ktlint-report.txt
        
        - uses: uploadReport@1.*
          name: 归档报告
          with:
            fileDir: src/backend/report
            indexFile: ktlint-report.txt
            indexFileCharset: UTF-8
            reportName: ktlint-report
            isParallel: false
            isSendEmail: false

        - name: "腾讯代码分析(最新)"
          uses: "CodeCCCheckAtom@1.*"
          with:
            languages:
            - "JAVA"
            - "KOTLIN"
            languageRuleSetMap:
              JAVA_RULE:
              - "codecc_default_java"
              KOTLIN_RULE:
              - "codecc_default_kotlin"
            path:
            - "src/backend"
