{{- if .Values.preview.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-preview
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: preview
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    {{- if keys $.Values.preview.config }}
    preview:
      {{- toYaml .Values.preview.config | nindent 6 }}
    {{- end}}
{{- end }}