{{- if .Values.fsserver.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-fs-server
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: fs-server
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    fs-server:
      domain: {{ .Values.bkDomainScheme }}://{{ .Values.gateway.host }}/fs-server
      {{- if keys $.Values.fsserver.config }}
        {{- toYaml .Values.fsserver.config | nindent 6 }}
      {{- end}}
{{- end }}