{{- if .Values.bkLogConfig.enabled }}

# gateway access log
apiVersion: bk.tencent.com/v1alpha1
kind: BkLogConfig
metadata:
  name: bk-repo-gateway-acsess-log-config
spec:
  dataId: {{ .Values.bkLogConfig.gatewayAccess.dataId }}
  logConfigType: container_log_config
  namespace: {{ .Release.Namespace }}
  labelSelector:
    matchLabels: {{- include "common.labels.standard" . | nindent 6 }}
      {{ include "bkrepo.labelValues.scope" . }}: {{ include "bkrepo.labelValues.scope.gateway" . }}
  path:
    - /data/workspace/logs/nginx/bkrepo.access.*.log
  extMeta:
    logSourceType: "gateway-access"

---
# gateway error log
apiVersion: bk.tencent.com/v1alpha1
kind: BkLogConfig
metadata:
  name: bk-repo-gateway-error-log-config
spec:
  dataId: {{ .Values.bkLogConfig.gatewayError.dataId }}

  logConfigType: container_log_config
  namespace: {{ .Release.Namespace }}
  labelSelector:
    matchLabels: {{- include "common.labels.standard" . | nindent 6 }}
      {{ include "bkrepo.labelValues.scope" . }}: {{ include "bkrepo.labelValues.scope.gateway" . }}
  path:
    - /data/workspace/logs/nginx/*.error.log
  extMeta:
    logSourceType: "gateway-error"

{{- end }}
