{{- if .Values.common.config.storage.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bkrepo-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - "lookupcache=pos"
  nfs:
    server: {{ .Values.common.config.storage.nfs.server }}
    path: {{ .Values.common.config.storage.nfs.path }}
{{- end -}}