{{- if .Values.common.config.storage.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bkrepo-nfs-pvc
spec:
  capacity:
    storage: ""
  accessModes:
    - ReadWriteMany
  volumeName: bkrepo-nfs-pv
{{- end -}}