{{- if .Values.common.config.storage.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bkrepo-nfs-pvc
spec:
  storageClassName: bkrepo-nfs
  resources:
    requests:
      storage: 100Ti
  accessModes:
    - ReadWriteMany
  volumeName: {{ include "common.names.fullname" . }}-nfs-pv
{{- end -}}