{{- if .Values.common.config.storage.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}-nfs-pvc
spec:
  storageClassName: bkrepo-nfs
  resources:
    requests:
      storage: {{ .Values.common.config.storage.nfs.capacity }}
  accessModes:
    - ReadWriteMany
  volumeName: {{ include "common.names.fullname" . }}-nfs-pv
{{- end -}}