{{- if .Values.replicationUDP.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-replication-udp
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: replication
    {{ include "bkrepo.labelValues.scope" . }}: {{ include "bkrepo.labelValues.scope.backend" . }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.replicationUDP.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
      {{- end }}
      {{- if .Values.replicationUDP.service.annotations }}
      {{- include "common.tplvalues.render" (dict "value" .Values.replicationUDP.service.annotations "context" $) | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  type: {{ .Values.replicationUDP.service.type }}
  ports:
    - name: fdtp
      port: {{ .Values.replicationUDP.service.port }}
      {{- if and .Values.replicationUDP.service.nodePort (or (eq .Values.replicationUDP.service.type "NodePort") (eq .Values.replicationUDP.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.replicationUDP.service.nodePort }}
      {{- else }}
      nodePort: null
      {{- end }}
      targetPort: fdtp
      protocol: UDP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: replication
{{- end }}
