package com.tencent.bkrepo.generic.constant

const val BKREPO_PREFIX = "X-BKREPO-"

const val HEADER_OVERWRITE = BKREPO_PREFIX + "OVERWRITE"
const val HEADER_SHA256 = BKREPO_PREFIX + "SHA256"
const val HEADER_MD5 = BKREPO_PREFIX + "MD5"
const val HEADER_EXPIRES = BKREPO_PREFIX + "EXPIRES"
const val HEADER_SIZE = BKREPO_PREFIX + "SIZE"
const val HEADER_UPLOAD_ID = BKREPO_PREFIX + "UPLOAD-ID"
const val HEADER_SEQUENCE = BKREPO_PREFIX + "SEQUENCE"

const val BKREPO_META_PREFIX = "X-BKREPO-META-"
const val BKREPO_META = "X-BKREPO-META"
