name: Build assembly application and test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ issue_2459 ]
    paths:
    - 'src/backend/**'
  pull_request:
    branches: [ issue_2459, release-* ]
    paths:
    - 'src/backend/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Start MongoDB
      run: |
        docker run -d --name mongodb -p 27017:27017 mongo
    - name: Gradle Build and test
      working-directory: src/backend/
      run: |
        ./gradlew clean
        ./gradlew boot-assembly:build -x test
        java -jar -Dlogging.path=boot-assembly/build/libs/bkrepo/logs -Dstorage.filesystem.path=boot-assembly/build/libs/bkrepo/bkrepo boot-assembly/build/libs/boot-assembly-1.0.0-RELEASE.jar &
        sleep 60
        curl http://localhost:8080/helm/blueking/helm-local/index.yaml
